version: "3.9"
services:
  backend:
    build:
      context: "/Users/x267834/Documents/Devops_With_Docker/Part2/example-backend"
      dockerfile: "/Users/x267834/Documents/Devops_With_Docker/Part2/example-backend/Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: "/Users/x267834/Documents/Devops_With_Docker/Part2/example-frontend"
      dockerfile: "/Users/x267834/Documents/Devops_With_Docker/Part2/example-frontend/Dockerfile"
    ports:
      - "5300:5300"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres  
    volumes:
      - ./database:/var/lib/postgresql/data