version: "3.9"
services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service:ubuntu
    volumes: 
      - "/Users/x267834/Documents/Devops_With_Docker/Part2/text.log:/usr/src/app/text.log"
    container_name: web-service
